### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectral-mpe-editor#7]
@zigen

Cannot build app.

## Expected Behavior

Generated app should work in the same behavior as you launch with 'npm start'.
App is generated at `./dist/mac`

## Current Behavior

Get error message on console of electron dev tools. 
```
Uncaught Error: Cannot find module '@babel/register'
    at Module._resolveFilename
```

## Possible Solution

Something related to Babel?

## Steps to Reproduce

1.  Install dependencies `npm i`
2. ` npm run dist`
3.  Open your app file at `./dist/mac`

**Comment by zigen** [comment]
this is difficult part of building electron apps.
you use babel-register at [here](https://github.com/szk2s/spectral-mpe-editor/blob/master/public/index.html#L41)
and this package put at [devDependencies](https://github.com/szk2s/spectral-mpe-editor/blob/master/package.json#L38)
the packages at devDependencies are not included in App (you can check it if you disable `asar` option). 
https://www.electron.build/configuration/configuration#overridable-per-platform-options

## solution
1. include babel-register and other packages at devDependencies which you need into app. (this means app transpiles your es6 code into es5 at runtime)
2. remove babel-register and transpiles your code  at build time

 I recommend 2, since it's more efficient way.

**Comment by szk2s** [comment]
@zigen Got another error message from terminal....
```
satoshisuzuki: spectral-mpe-editor $npm run dist

> spectral-mpe-editor@0.1.0 dist /Users/satoshisuzuki/git/spectral-mpe-editor
> electron-builder

  • electron-builder version=20.38.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.0.0 appOutDir=dist/mac
Error: Application entry file "../public/main.js" in the "/Users/satoshisuzuki/git/spectral-mpe-editor/dist/mac/spectral-mpe-editor.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/out/asar/asarFileChecker.js:44:14)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at _checkFileInArchive (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:36:17)
    at checkFileInArchive (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/out/asar/asarFileChecker.js:40:30)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:406:110)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:446:92)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.doPack (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/satoshisuzuki/git/spectral-mpe-editor/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spectral-mpe-editor@0.1.0 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spectral-mpe-editor@0.1.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/satoshisuzuki/.npm/_logs/2018-12-29T03_18_29_485Z-debug.log

```

**Comment by szk2s** [comment]
I have the entry file at the path. But builder seems unable to detect it ...
```
Error: Application entry file "public/main.js" in the "/Users/satoshisuzuki/git/spectral-mpe-editor/dist/mac/spectral-mpe-editor.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
```

**Comment by zigen** [comment]
you need to put `main.js` under `app/` dir

**Comment by szk2s** [comment]
Okay, Thanks. Now I am attempting to build with web pack at `dist` branch

**Comment by szk2s** [comment]
Sorry, @zigen 
I have done the bundling with webpack. But I cannot build app with electron-builder.
Can you please see my `dist` brunch?
`./app/dist/main.js` is the bundled and transpiled js file (renderer process).
also I manually copied my `public` folder into `app` dir.

**Comment by zigen** [comment]
will take a look later.

**Comment by szk2s** [comment]
Thank you @zigen . I appreciate your help.
## Current Behavior

Get error message on console of electron dev tools. 
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
```
## Steps to Reproduce


1. `git checkout dist`
1.  Install dependencies `npm i`
1. ` npm run dist`
1.  Open your app file at `./dist/mac`
