### ISSUE TITLE
Cannot use ESLint and Prettier at the same time

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectral-mpe-editor#8]
Cannot use ESLint and Prettier at the same time 
## Expected Behavior

Developer can use ESLint and Prettier 
## Current Behavior

Get error message when you use eslint even if you've already installed 'eslint-config-prettier'. 
```
Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/satoshisuzuki/git/spectral-mpe-editor/.eslintrc.js
    at ModuleResolver.resolve (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:484:28)
    at load (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:528:22)
    at Object.load (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/satoshisuzuki/.nodebrew/node/v10.14.2/lib/node_modules/eslint/lib/config.js:192:43)
```
## Steps to Reproduce

1.  Install dependencies `npm i`
2.  `eslint src/App.js`

**Comment by zigen** [comment]
hey @szk2s , which branch can I reproduce?

**Comment by szk2s** [comment]
Sorry Master is up-to-date

**Comment by szk2s** [comment]
dist is now trying to build with webpack.

**Comment by zigen** [comment]
Okay, I'll try it. Thanks!

**Comment by zigen** [comment]
first of all, you need to understand how node package solves its dependencies.
https://docs.npmjs.com/cli/install

if you install eslint globally, eslint search eslint-plugin-XXX in global context.
I mean if you install eslint globally, you must also install eslint-plugin-XXX globally.
contrary, if you install eslint locally like `$ npm install --save/--save-dev eslint`, you must install plugins locally. (locally means installed at `node_modules` dir in your package root) 

I recommend latter way. if you install those packages locally, your eslint is at `node_modules/eslint` (symbolic link of eslit is in `node_modules/.bin`.) and also other plugins are at `node_modules/`.
local your eslint searches plugins under `node_modules/`.

Be careful, if you installed in both ways, which eslint called depends on your `PATH`.
writing [npm-run-script](https://docs.npmjs.com/misc/scripts) solves this problem, since always local one is called if you use npm-run-script.
